import { Button, Stack, TextField } from '@mui/material';
import { Box } from '@mui/system';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useCallback, useMemo, useState } from 'react';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
    const [state, setState] = useState({ roomName: '', userName: '' });
    const [test, setTest] = useState(true);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Stack
                sx={{
                    width: '100vw',
                    height: '100vh',
                    justifyContent: 'center',
                    alignItems: 'center',
                    flexDirection: 'column',
                    backgroundColor: '#000000',
                }}
            >
                <Box
                    sx={{
                        width: '300px',
                        display: 'flex',
                        justifyContent: 'center',
                        alignItems: 'center',
                        flexDirection: 'column',
                    }}
                >
                    <TextField
                        sx={{ '& input': { color: '#fff' } }}
                        placeholder='Room Name'
                        label='Room Name'
                        margin='normal'
                        value={state.roomName}
                        onChange={(e) => {
                            setState({ ...state, roomName: e.target.value });
                        }}
                        color='error'
                        focused
                        fullWidth
                    />
                    <TextField
                        sx={{ '& input': { color: '#fff' } }}
                        margin='normal'
                        value={state.userName}
                        onChange={(e) => {
                            setState({ ...state, userName: e.target.value });
                        }}
                        placeholder='User Name'
                        label='User Name'
                        color='error'
                        focused
                        fullWidth
                    />
                    <Button
                        sx={{ marginTop: '18px' }}
                        variant='contained'
                        fullWidth
                        color='error'
                    >
                        Chat
                    </Button>
                </Box>
                {test ? (
                    <Button
                        sx={{ marginTop: '16px' }}
                        variant='contained'
                        color='error'
                        onClick={() => setTest((prev) => !prev)}
                    >
                        URL
                    </Button>
                ) : (
                    <TextField
                        sx={{ '& input': { color: '#fff' } }}
                        margin='normal'
                        value={state.userName}
                        onChange={(e) => {
                            setState({ ...state, userName: e.target.value });
                            if (e.target.value === 'test') setTest(true);
                        }}
                        placeholder='User Name'
                        label='User Name'
                        color='error'
                        focused
                    />
                )}
            </Stack>
        </>
    );
};

export default Home;
