import { Button, Stack, TextField } from '@mui/material';
import { Box } from '@mui/system';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { useCallback, useContext, useEffect, useMemo, useState } from 'react';
import { Context } from '../shared/context/authcontext';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
    const [state, setState] = useState({
        userId: '',
        url: '',
        roomName: '',
        livekiturl: '',
    });

    const router = useRouter();

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Stack
                sx={{
                    width: '100vw',
                    height: '100vh',
                    justifyContent: 'center',
                    alignItems: 'center',
                    flexDirection: 'column',
                    backgroundColor: '#000000',
                }}
            >
                <Box
                    sx={{
                        width: '300px',
                        display: 'flex',
                        justifyContent: 'center',
                        alignItems: 'center',
                        flexDirection: 'column',
                    }}
                >
                    <TextField
                        sx={{ '& input': { color: '#fff' } }}
                        placeholder='Some Number'
                        label='User Id'
                        name='userId'
                        margin='normal'
                        value={state.userId}
                        onChange={(e) => {
                            setState({
                                ...state,
                                [e.target.name]: e.target.value,
                            });
                        }}
                        color='error'
                        focused
                        fullWidth
                    />
                    <TextField
                        sx={{ '& input': { color: '#fff' } }}
                        margin='normal'
                        value={state.url}
                        name='url'
                        onChange={(e) => {
                            setState({
                                ...state,
                                [e.target.name]: e.target.value,
                            });
                        }}
                        placeholder='someurl.com'
                        label='URL'
                        color='error'
                        focused
                        fullWidth
                    />
                    <TextField
                        sx={{ '& input': { color: '#fff' } }}
                        margin='normal'
                        value={state.roomName}
                        name='roomName'
                        onChange={(e) => {
                            setState({
                                ...state,
                                [e.target.name]: e.target.value,
                            });
                        }}
                        placeholder='Dinning hall'
                        label='Room Name'
                        color='error'
                        focused
                        fullWidth
                    />
                    <TextField
                        sx={{ '& input': { color: '#fff' } }}
                        margin='normal'
                        value={state.livekiturl}
                        name='livekiturl'
                        onChange={(e) => {
                            setState({
                                ...state,
                                [e.target.name]: e.target.value,
                            });
                        }}
                        placeholder='Dinning hall'
                        label='livekit URL'
                        color='error'
                        focused
                        fullWidth
                    />
                    <Button
                        sx={{ marginTop: '18px' }}
                        variant='contained'
                        fullWidth
                        color='error'
                        onClick={() => {
                            router.push({
                                pathname: '/room',
                                query: {
                                    ...state,
                                },
                            });
                        }}
                    >
                        Chat
                    </Button>
                </Box>
            </Stack>
        </>
    );
};

export default Home;
